export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_DEFAULT = 'REGISTER_DEFAULT';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_DEFAULT = 'LOGIN_DEFAULT';

export const SET_FIRST_LOAD_FALSE = 'SET_FIRST_LOAD_FALSE'
export const SET_FIRST_LOAD_TRUE = 'SET_FIRST_LOAD_TRUE'

export const GET_PROFILE_USER_LOADING = 'GET_PROFILE_USER_LOADING';
export const GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS';
export const GET_PROFILE_USER_FAILED = 'GET_PROFILE_USER_FAILED';
export const GET_PROFILE_USER_DEFAULT = 'GET_PROFILE_USER_DEFAULT';

export const CEK_PRIVATE_KEY_LOADING = 'CEK_PRIVATE_KEY_LOADING';
export const CEK_PRIVATE_KEY_SUCCESS = 'CEK_PRIVATE_KEY_SUCCESS';
export const CEK_PRIVATE_KEY_FAILED = 'CEK_PRIVATE_KEY_FAILED';

export const CEK_PUBLIC_KEY_LOADING = 'CEK_PUBLIC_KEY_LOADING';
export const CEK_PUBLIC_KEY_SUCCESS = 'CEK_PUBLIC_KEY_SUCCESS';
export const CEK_PUBLIC_KEY_FAILED = 'CEK_PUBLIC_KEY_FAILED';